# Generated by Django 6.0.5 on 2026-06-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1.0 Knowledge collection',
                'verbose_name_plural': '1.0 Knowledge collections - knowledge groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=140)),
                ('temperature_default', models.DecimalField(decimal_places=2, default=0.7, max_digits=4)),
                ('max_tokens_default', models.PositiveIntegerField(default=1000)),
                ('supports_tools', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '0.2 Model config',
                'verbose_name_plural': '0.2 Model configs - model choices',
                'ordering': ['provider__name', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('deepseek', 'DeepSeek'), ('anthropic', 'Anthropic'), ('other', 'Other')], max_length=30)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_env_var', models.CharField(blank=True, max_length=100)),
                ('default_timeout', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '0.1 Provider config',
                'verbose_name_plural': '0.1 Provider configs - AI service accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('tool_kind', models.CharField(choices=[('http', 'HTTP'), ('python_callable', 'Python Callable'), ('prompt_macro', 'Prompt Macro')], max_length=30)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '2.0 Tool definition',
                'verbose_name_plural': '2.0 Tool definitions - optional agent tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('role', models.CharField(max_length=140)),
                ('system_prompt', models.TextField(blank=True)),
                ('knowledge_max_chars', models.PositiveIntegerField(default=6000)),
                ('input_contract', models.JSONField(blank=True, default=dict)),
                ('output_contract', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('execution_mode', models.CharField(choices=[('sync', 'Sync'), ('async', 'Async'), ('inherit', 'Inherit')], default='inherit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_collections', models.ManyToManyField(blank=True, related_name='agents', to='ai_hub.knowledgecollection')),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='ai_hub.modelconfig')),
                ('tools', models.ManyToManyField(blank=True, related_name='agents', to='ai_hub.tooldefinition')),
            ],
            options={
                'verbose_name': '3.0 Agent profile',
                'verbose_name_plural': '3.0 Agent profiles - prompts and roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('global_input_contract', models.JSONField(blank=True, default=dict)),
                ('global_output_contract', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_for_pipelines', to='ai_hub.agentprofile')),
            ],
            options={
                'verbose_name': '4.0 Pipeline definition',
                'verbose_name_plural': '4.0 Pipeline definitions - ordered agent flows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('runtime_kind', models.CharField(choices=[('orchestrator', 'Orchestrator'), ('game', 'GAME')], default='orchestrator', max_length=20)),
                ('runtime_mode', models.CharField(choices=[('sync', 'Sync'), ('async', 'Async'), ('hybrid', 'Hybrid')], default='async', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_async', 'Waiting Async Continuation'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('goal_text', models.TextField(blank=True)),
                ('runtime_config', models.JSONField(blank=True, default=dict)),
                ('initial_context', models.JSONField(blank=True, default=dict)),
                ('final_context', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_execution_sessions', to='ai_hub.agentprofile')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_hub_execution_sessions', to='contenttypes.contenttype')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_ai_hub_sessions', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_sessions', to='ai_hub.pipelinedefinition')),
            ],
            options={
                'verbose_name': '5.0 Execution session',
                'verbose_name_plural': '5.0 Execution sessions - generic runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('input_mapping', models.JSONField(blank=True, default=dict)),
                ('output_mapping', models.JSONField(blank=True, default=dict)),
                ('on_error', models.CharField(choices=[('stop', 'Stop'), ('continue', 'Continue'), ('fallback_agent', 'Fallback Agent')], default='stop', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_steps', to='ai_hub.agentprofile')),
                ('fallback_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_steps', to='ai_hub.agentprofile')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai_hub.pipelinedefinition')),
            ],
            options={
                'verbose_name': '4.1 Pipeline step',
                'verbose_name_plural': '4.1 Pipeline steps - agent connections',
                'ordering': ['pipeline__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('action_name', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('observation_payload', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_step_runs', to='ai_hub.agentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='ai_hub.executionsession')),
                ('pipeline_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_step_runs', to='ai_hub.pipelinestep')),
            ],
            options={
                'verbose_name': '5.1 Execution step run',
                'verbose_name_plural': '5.1 Execution step runs - generic step logs',
                'ordering': ['session_id', 'order'],
            },
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_hub.providerconfig'),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('curated_text', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, upload_to='ai_hub/knowledge/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai_hub.knowledgecollection')),
            ],
            options={
                'verbose_name': '1.1 Knowledge document',
                'verbose_name_plural': '1.1 Knowledge documents - curated files and text',
                'ordering': ['collection__name', 'title'],
                'indexes': [models.Index(fields=['collection', 'status'], name='ai_hub_kdoc_collect_status_idx'), models.Index(fields=['language', 'status'], name='ai_hub_kdoc_lang_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='executionsession',
            index=models.Index(fields=['runtime_kind', 'status'], name='ai_hub_session_kind_status_idx'),
        ),
        migrations.AddIndex(
            model_name='executionsession',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='ai_hub_session_source_idx'),
        ),
        migrations.AddIndex(
            model_name='executionsession',
            index=models.Index(fields=['created_at'], name='ai_hub_session_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestep',
            unique_together={('pipeline', 'order')},
        ),
        migrations.AddIndex(
            model_name='executionsteprun',
            index=models.Index(fields=['session', 'status'], name='ai_hub_step_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='executionsteprun',
            index=models.Index(fields=['agent', 'status'], name='ai_hub_step_agent_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='executionsteprun',
            unique_together={('session', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='modelconfig',
            unique_together={('provider', 'model_name')},
        ),
    ]
