# Generated by Django 6.0.6 on 2026-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerconfig',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('deepseek', 'DeepSeek'), ('anthropic', 'Anthropic'), ('training', 'Training (stub)'), ('other', 'Other')], max_length=30),
        ),
    ]
