# Generated by Django 6.0.6 on 2026-06-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0002_alter_providerconfig_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_policy', models.JSONField(blank=True, default=dict)),
                ('default_runtime_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '4.5 GAME workspace',
                'verbose_name_plural': '4.5 GAME workspaces - environments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_info', 'Waiting for information'), ('waiting_approval', 'Waiting for approval'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30)),
                ('base_priority', models.PositiveIntegerField(default=50)),
                ('calculated_priority', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('success_criteria', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='ai_hub.gameworkspace')),
            ],
            options={
                'verbose_name': '4.6 GAME goal',
                'verbose_name_plural': '4.6 GAME goals - work items',
                'ordering': ['workspace__name', '-calculated_priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameGoalDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='ai_hub.gamegoal')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='ai_hub.gamegoal')),
            ],
            options={
                'verbose_name': '4.7 GAME goal dependency',
                'verbose_name_plural': '4.7 GAME goal dependencies',
                'ordering': ['goal_id', 'depends_on_id'],
                'constraints': [models.UniqueConstraint(fields=('goal', 'depends_on'), name='ai_hub_unique_goal_dependency'), models.CheckConstraint(condition=models.Q(('goal', models.F('depends_on')), _negated=True), name='ai_hub_goal_dependency_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='gamegoal',
            index=models.Index(fields=['workspace', 'status'], name='aihub_goal_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='gamegoal',
            index=models.Index(fields=['workspace', 'calculated_priority'], name='aihub_goal_ws_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='gamegoal',
            index=models.Index(fields=['due_at'], name='ai_hub_goal_due_idx'),
        ),
    ]
