# Generated by Django 6.0.6 on 2026-06-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0003_gameworkspace_gamegoal_gamegoaldependency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionsession',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_sessions', to='ai_hub.gamegoal'),
        ),
    ]
