# Generated by Django 6.0.6 on 2026-06-20 20:29

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0004_executionsession_goal'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executionsession',
            name='goal_outcome_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gamegoal',
            name='queued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamegoal',
            name='transition_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gamegoal',
            name='base_priority',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(999900)]),
        ),
        migrations.AlterField(
            model_name='gamegoal',
            name='calculated_priority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999.99)]),
        ),
        migrations.AddConstraint(
            model_name='executionsession',
            constraint=models.UniqueConstraint(condition=models.Q(('goal__isnull', False), ('status__in', ['pending', 'running', 'waiting_async'])), fields=('goal',), name='aihub_unique_active_goal'),
        ),
    ]
