# Generated by Django 6.0.6 on 2026-06-21 00:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def prepare_constraint_data(apps, schema_editor):
    """Preserve legacy rows while normalising shapes required by new constraints."""
    Continuation = apps.get_model("ai_hub", "GameContinuationRequest")
    duplicate_session_ids = list(
        Continuation.objects.filter(status="pending")
        .values_list("session_id", flat=True)
        .order_by()
        .distinct()
    )
    for session_id in duplicate_session_ids:
        pending_ids = list(
            Continuation.objects.filter(session_id=session_id, status="pending")
            .order_by("-created_at", "-pk")
            .values_list("pk", flat=True)
        )
        if len(pending_ids) > 1:
            Continuation.objects.filter(pk__in=pending_ids[1:]).update(status="cancelled")

    Memory = apps.get_model("ai_hub", "GameMemoryEntry")
    Memory.objects.filter(importance_score__lt=Decimal("0.00")).update(
        importance_score=Decimal("0.00")
    )
    Memory.objects.filter(importance_score__gt=Decimal("1.00")).update(
        importance_score=Decimal("1.00")
    )
    Memory.objects.filter(scope_type="workspace").update(goal_id=None, session_id=None)
    for entry in Memory.objects.filter(scope_type__in=["goal", "action_result"], goal_id=None):
        session_goal_id = None
        if entry.session_id:
            session_goal_id = getattr(entry.session, "goal_id", None)
        if session_goal_id:
            entry.goal_id = session_goal_id
            entry.save(update_fields=["goal_id"])
        else:
            entry.scope_type = "workspace"
            entry.session_id = None
            entry.save(update_fields=["scope_type", "session_id"])
    for entry in Memory.objects.filter(scope_type="session", session_id=None):
        entry.scope_type = "goal" if entry.goal_id else "workspace"
        entry.save(update_fields=["scope_type"])
    for entry in Memory.objects.filter(scope_type__in=["goal", "action_result"]):
        update_fields = []
        if entry.goal_id and entry.workspace_id != entry.goal.workspace_id:
            entry.workspace_id = entry.goal.workspace_id
            update_fields.append("workspace_id")
        if entry.session_id and entry.session.goal_id != entry.goal_id:
            entry.session_id = None
            update_fields.append("session_id")
        if update_fields:
            entry.save(update_fields=update_fields)
    for entry in Memory.objects.filter(scope_type="session", session_id__isnull=False):
        update_fields = []
        session_goal = entry.session.goal
        if session_goal is not None:
            if entry.workspace_id != session_goal.workspace_id:
                entry.workspace_id = session_goal.workspace_id
                update_fields.append("workspace_id")
            if entry.goal_id and entry.goal_id != session_goal.pk:
                entry.goal_id = session_goal.pk
                update_fields.append("goal_id")
        elif entry.goal_id:
            entry.goal_id = None
            update_fields.append("goal_id")
        if update_fields:
            entry.save(update_fields=update_fields)
    Memory.objects.exclude(
        scope_type__in=["workspace", "goal", "session", "action_result"]
    ).update(scope_type="workspace", goal_id=None, session_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0010_phase09_workspace_action_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameactionrun',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_action_runs', to='ai_hub.gameactiondefinition'),
        ),
        migrations.AlterField(
            model_name='gameactionrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_action_runs', to='ai_hub.executionsession'),
        ),
        migrations.AlterField(
            model_name='gamememoryentry',
            name='importance_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.RunPython(prepare_constraint_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='gamecontinuationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('session',), name='aihub_one_pending_continuation'),
        ),
        migrations.AddConstraint(
            model_name='gamememoryentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('goal__isnull', True), ('scope_type', 'workspace'), ('session__isnull', True)), models.Q(('goal__isnull', False), ('scope_type__in', ['goal', 'action_result'])), models.Q(('scope_type', 'session'), ('session__isnull', False)), _connector='OR'), name='aihub_memory_scope_shape'),
        ),
    ]
