# Generated by Django 6.0.6 on 2026-06-21 19:12

from django.db import migrations, models


def prepare_plan_and_delegation_constraints(apps, schema_editor):
    Plan = apps.get_model("ai_hub", "GameGoalPlan")
    Step = apps.get_model("ai_hub", "GameGoalPlanStep")
    Delegation = apps.get_model("ai_hub", "GameDelegationRun")

    Plan.objects.filter(version__lt=1).update(version=1)
    Step.objects.filter(depends_on_step_id=models.F("pk")).update(depends_on_step_id=None)
    for plan_id in Step.objects.values_list("plan_id", flat=True).order_by().distinct():
        steps = list(Step.objects.filter(plan_id=plan_id).order_by("order", "pk"))
        if any(step.order < 1 for step in steps):
            # Move through a collision-free temporary range before assigning 1..N.
            for offset, step in enumerate(steps, start=1):
                Step.objects.filter(pk=step.pk).update(order=1000000 + offset)
            for offset, step in enumerate(steps, start=1):
                Step.objects.filter(pk=step.pk).update(order=offset)
            steps = list(Step.objects.filter(plan_id=plan_id).order_by("order", "pk"))
        steps_by_id = {step.pk: step for step in steps}
        for step in steps:
            dependency = steps_by_id.get(step.depends_on_step_id)
            if step.depends_on_step_id and (
                dependency is None or dependency.order >= step.order
            ):
                Step.objects.filter(pk=step.pk).update(depends_on_step_id=None)

    Delegation.objects.filter(
        status__in=["success", "failed"], finished_at__isnull=True
    ).update(finished_at=models.F("created_at"))
    Delegation.objects.filter(
        status__in=["pending", "running"], finished_at__isnull=False
    ).update(finished_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0012_phase10_plans_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegoalplan',
            name='revision_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            prepare_plan_and_delegation_constraints,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='gamedelegationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status__in', ['pending', 'running'])), models.Q(('finished_at__isnull', False), ('status__in', ['success', 'failed'])), _connector='OR'), name='aihub_delegation_terminal_time'),
        ),
        migrations.AddConstraint(
            model_name='gamegoalplan',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='aihub_plan_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='gamegoalplanstep',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='aihub_plan_step_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='gamegoalplanstep',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('depends_on_step')), _negated=True), name='aihub_plan_step_not_self'),
        ),
    ]
