# Generated by Django 6.0.6 on 2026-06-22 23:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0013_stabilize_phases_10_12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='temperature_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.70'), max_digits=4),
        ),
    ]
