# Generated by Django 6.0.6 on 2026-06-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0014_alter_modelconfig_temperature_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '2.1 Toolbox',
                'verbose_name_plural': '2.1 Toolboxes - reusable tool groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='is_system_tool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='operation_mode',
            field=models.CharField(choices=[('read', 'Read'), ('draft_write', 'Draft write'), ('state_write', 'State write'), ('external_write', 'External write'), ('execute', 'Execute')], default='read', max_length=30),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentToolGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('permission_level', models.CharField(choices=[('use', 'Use'), ('read_only', 'Read only'), ('draft_write', 'Draft write'), ('state_write', 'State write'), ('external_write', 'External write'), ('execute', 'Execute')], default='use', max_length=30)),
                ('requires_approval_override', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_grants', to='ai_hub.agentprofile')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_grants', to='ai_hub.tooldefinition')),
            ],
            options={
                'verbose_name': '3.2 Agent tool grant',
                'verbose_name_plural': '3.2 Agent tool grants - individual overrides',
                'ordering': ['agent__name', 'tool__name'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'tool'), name='ai_hub_unique_agent_tool_grant')],
            },
        ),
        migrations.CreateModel(
            name='AgentToolboxAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_assignments', to='ai_hub.agentprofile')),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='ai_hub.toolbox')),
            ],
            options={
                'verbose_name': '3.1 Agent toolbox assignment',
                'verbose_name_plural': '3.1 Agent toolbox assignments - reusable access',
                'ordering': ['agent__name', 'toolbox__name'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'toolbox'), name='ai_hub_unique_agent_toolbox')],
            },
        ),
        migrations.CreateModel(
            name='ToolboxTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('default_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_entries', to='ai_hub.tooldefinition')),
                ('toolbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_entries', to='ai_hub.toolbox')),
            ],
            options={
                'verbose_name': '2.2 Toolbox tool',
                'verbose_name_plural': '2.2 Toolbox tools - toolbox membership',
                'ordering': ['toolbox__name', 'display_order', 'tool__name'],
                'constraints': [models.UniqueConstraint(fields=('toolbox', 'tool'), name='ai_hub_unique_toolbox_tool')],
            },
        ),
        migrations.CreateModel(
            name='ToolExecutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('approval_state', models.CharField(choices=[('not_required', 'Not required'), ('required', 'Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=30)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_execution_runs', to='ai_hub.agentprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_execution_runs', to='ai_hub.executionsession')),
                ('step_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_execution_runs', to='ai_hub.executionsteprun')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_runs', to='ai_hub.tooldefinition')),
            ],
            options={
                'verbose_name': '5.2 Tool execution run',
                'verbose_name_plural': '5.2 Tool execution runs - generic tool audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='aihub_tool_run_sess_status_idx'), models.Index(fields=['agent', 'status'], name='aihub_tool_run_agent_stat_idx'), models.Index(fields=['tool', 'status'], name='aihub_tool_run_tool_stat_idx')],
            },
        ),
    ]
