# Generated by Django 6.0.6 on 2026-06-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0015_toolbox_tooldefinition_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameactiondefinition',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_action_definitions', to='ai_hub.tooldefinition'),
        ),
    ]
