# Generated by Django 6.0.6 on 2026-06-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0016_gameactiondefinition_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('section_title', models.CharField(blank=True, max_length=240)),
                ('content', models.TextField()),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_hub.knowledgedocument')),
            ],
            options={
                'verbose_name': '1.2 Knowledge document chunk',
                'verbose_name_plural': '1.2 Knowledge document chunks - retrievable sections',
                'ordering': ['document__collection__name', 'document__title', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='aihub_kchunk_doc_idx'), models.Index(fields=['section_title'], name='aihub_kchunk_section_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='ai_hub_unique_doc_chunk_index')],
            },
        ),
    ]
