# Generated by Django 6.0.6 on 2026-06-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0017_knowledgedocumentchunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'ordering': ['name'], 'verbose_name': '1.9 Agent profile', 'verbose_name_plural': '1.9 Agent profiles - prompts and roles'},
        ),
        migrations.AlterModelOptions(
            name='agenttoolboxassignment',
            options={'ordering': ['agent__name', 'toolbox__name'], 'verbose_name': '1.10 Agent toolbox assignment', 'verbose_name_plural': '1.10 Agent toolbox assignments - reusable access'},
        ),
        migrations.AlterModelOptions(
            name='agenttoolgrant',
            options={'ordering': ['agent__name', 'tool__name'], 'verbose_name': '1.11 Agent tool grant', 'verbose_name_plural': '1.11 Agent tool grants - individual overrides'},
        ),
        migrations.AlterModelOptions(
            name='executionsession',
            options={'ordering': ['-created_at'], 'verbose_name': '4.1 Execution session', 'verbose_name_plural': '4.1 Execution sessions - generic runs'},
        ),
        migrations.AlterModelOptions(
            name='executionsteprun',
            options={'ordering': ['session_id', 'order'], 'verbose_name': '4.2 Execution step run', 'verbose_name_plural': '4.2 Execution step runs - generic step logs'},
        ),
        migrations.AlterModelOptions(
            name='gameactionapprovalrequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_game_action', 'Can approve GAME action requests')], 'verbose_name': '4.7 GAME action approval request', 'verbose_name_plural': '4.7 GAME action approval requests - gated actions'},
        ),
        migrations.AlterModelOptions(
            name='gameactiondefinition',
            options={'ordering': ['name'], 'verbose_name': '3.6 GAME action definition', 'verbose_name_plural': '3.6 GAME action definitions - dispatcher registry'},
        ),
        migrations.AlterModelOptions(
            name='gameactionrun',
            options={'ordering': ['session_id', 'iteration'], 'verbose_name': '4.4 GAME action run', 'verbose_name_plural': '4.4 GAME action runs - dispatcher history'},
        ),
        migrations.AlterModelOptions(
            name='gamecontinuationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '4.6 GAME continuation request', 'verbose_name_plural': '4.6 GAME continuation requests - pause records'},
        ),
        migrations.AlterModelOptions(
            name='gamedelegationrun',
            options={'ordering': ['-created_at'], 'verbose_name': '4.5 GAME delegation run', 'verbose_name_plural': '4.5 GAME delegation runs - sub-agent history'},
        ),
        migrations.AlterModelOptions(
            name='gamegoal',
            options={'ordering': ['workspace__name', '-calculated_priority', 'created_at'], 'verbose_name': '3.2 GAME goal', 'verbose_name_plural': '3.2 GAME goals - work items'},
        ),
        migrations.AlterModelOptions(
            name='gamegoaldependency',
            options={'ordering': ['goal_id', 'depends_on_id'], 'verbose_name': '3.3 GAME goal dependency', 'verbose_name_plural': '3.3 GAME goal dependencies'},
        ),
        migrations.AlterModelOptions(
            name='gamegoalplan',
            options={'ordering': ['-created_at'], 'verbose_name': '3.4 GAME goal plan', 'verbose_name_plural': '3.4 GAME goal plans - structured execution aids'},
        ),
        migrations.AlterModelOptions(
            name='gamegoalplanstep',
            options={'ordering': ['plan_id', 'order'], 'verbose_name': '3.5 GAME goal plan step', 'verbose_name_plural': '3.5 GAME goal plan steps'},
        ),
        migrations.AlterModelOptions(
            name='gamememoryentry',
            options={'ordering': ['workspace_id', '-importance_score', 'created_at'], 'verbose_name': '3.9 GAME memory entry', 'verbose_name_plural': '3.9 GAME memory entries - scoped knowledge store'},
        ),
        migrations.AlterModelOptions(
            name='gameworkspace',
            options={'ordering': ['name'], 'verbose_name': '3.1 GAME workspace', 'verbose_name_plural': '3.1 GAME workspaces - environments'},
        ),
        migrations.AlterModelOptions(
            name='gameworkspaceaction',
            options={'ordering': ['workspace__name', 'action__name'], 'verbose_name': '3.7 GAME workspace action', 'verbose_name_plural': '3.7 GAME workspace actions - allow-list'},
        ),
        migrations.AlterModelOptions(
            name='gameworkspaceagent',
            options={'ordering': ['workspace__name', 'agent__name'], 'verbose_name': '3.8 GAME workspace agent', 'verbose_name_plural': '3.8 GAME workspace agents - allow-list'},
        ),
        migrations.AlterModelOptions(
            name='knowledgecollection',
            options={'ordering': ['name'], 'verbose_name': '1.3 Knowledge collection', 'verbose_name_plural': '1.3 Knowledge collections - knowledge groups'},
        ),
        migrations.AlterModelOptions(
            name='knowledgedocument',
            options={'ordering': ['collection__name', 'title'], 'verbose_name': '1.4 Knowledge document', 'verbose_name_plural': '1.4 Knowledge documents - curated files and text'},
        ),
        migrations.AlterModelOptions(
            name='knowledgedocumentchunk',
            options={'ordering': ['document__collection__name', 'document__title', 'chunk_index'], 'verbose_name': '1.5 Knowledge document chunk', 'verbose_name_plural': '1.5 Knowledge document chunks - retrievable sections'},
        ),
        migrations.AlterModelOptions(
            name='modelconfig',
            options={'ordering': ['provider__name', 'model_name'], 'verbose_name': '1.2 Model config', 'verbose_name_plural': '1.2 Model configs - model choices'},
        ),
        migrations.AlterModelOptions(
            name='pipelinedefinition',
            options={'ordering': ['name'], 'verbose_name': '2.1 Pipeline definition', 'verbose_name_plural': '2.1 Pipeline definitions - ordered agent flows'},
        ),
        migrations.AlterModelOptions(
            name='pipelinestep',
            options={'ordering': ['pipeline__name', 'order'], 'verbose_name': '2.2 Pipeline step', 'verbose_name_plural': '2.2 Pipeline steps - agent connections'},
        ),
        migrations.AlterModelOptions(
            name='providerconfig',
            options={'ordering': ['name'], 'verbose_name': '1.1 Provider config', 'verbose_name_plural': '1.1 Provider configs - AI service accounts'},
        ),
        migrations.AlterModelOptions(
            name='toolbox',
            options={'ordering': ['name'], 'verbose_name': '1.7 Toolbox', 'verbose_name_plural': '1.7 Toolboxes - reusable tool groups'},
        ),
        migrations.AlterModelOptions(
            name='toolboxtool',
            options={'ordering': ['toolbox__name', 'display_order', 'tool__name'], 'verbose_name': '1.8 Toolbox tool', 'verbose_name_plural': '1.8 Toolbox tools - toolbox membership'},
        ),
        migrations.AlterModelOptions(
            name='tooldefinition',
            options={'ordering': ['name'], 'verbose_name': '1.6 Tool definition', 'verbose_name_plural': '1.6 Tool definitions - optional agent tools'},
        ),
        migrations.AlterModelOptions(
            name='toolexecutionrun',
            options={'ordering': ['-created_at'], 'verbose_name': '4.3 Tool execution run', 'verbose_name_plural': '4.3 Tool execution runs - generic tool audit'},
        ),
    ]
