# Generated by Django 6.0.6 on 2026-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0019_retrieval_first_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameactionapprovalrequest',
            name='execution_intent_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gameactionapprovalrequest',
            name='execution_intent_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
