# Generated by Django 6.1 on 2026-08-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0020_approval_execution_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='chunk_authority_mode',
            field=models.CharField(choices=[('unknown', 'Unknown (legacy or ungoverned)'), ('derived', 'Derived from a source'), ('explicit', 'Explicitly authored')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='generation_chunk_set_fingerprint',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='generation_input_fingerprint',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='generator_identity',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='generator_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
