# Generated by Django 6.1 on 2026-08-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0021_knowledge_lifecycle_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id_snapshot', models.PositiveBigIntegerField()),
                ('collection_id_snapshot', models.PositiveBigIntegerField()),
                ('operation', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('principal_kind', models.CharField(choices=[('human', 'Human operator'), ('system', 'System or service')], max_length=20)),
                ('principal_identifier', models.CharField(max_length=150)),
                ('previous_authority_mode', models.CharField(max_length=20)),
                ('new_authority_mode', models.CharField(max_length=20)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('previous_generation_input_fingerprint', models.CharField(blank=True, max_length=80)),
                ('new_generation_input_fingerprint', models.CharField(blank=True, max_length=80)),
                ('previous_generation_chunk_set_fingerprint', models.CharField(blank=True, max_length=80)),
                ('new_generation_chunk_set_fingerprint', models.CharField(blank=True, max_length=80)),
                ('previous_generator_identity', models.CharField(blank=True, max_length=64)),
                ('new_generator_identity', models.CharField(blank=True, max_length=64)),
                ('previous_generator_version', models.PositiveIntegerField(blank=True, null=True)),
                ('new_generator_version', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_chunk_count', models.PositiveIntegerField()),
                ('new_chunk_count', models.PositiveIntegerField()),
                ('previous_observed_input_fingerprint', models.CharField(blank=True, max_length=80)),
                ('new_observed_input_fingerprint', models.CharField(blank=True, max_length=80)),
                ('previous_observed_chunk_set_fingerprint', models.CharField(blank=True, max_length=80)),
                ('new_observed_chunk_set_fingerprint', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to='ai_hub.knowledgedocument')),
            ],
            options={
                'verbose_name': '1.12 Knowledge lifecycle event',
                'verbose_name_plural': '1.12 Knowledge lifecycle events - corpus mutation history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['document_id_snapshot', 'created_at'], name='aihub_klc_evt_docsnap_idx'), models.Index(fields=['operation', 'created_at'], name='aihub_klc_evt_op_time_idx')],
            },
        ),
    ]
