# Generated by Django 6.1 on 2026-08-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0025_application_scope_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_embeddings', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1.2b Provider grant',
                'verbose_name_plural': '1.2b Provider grants - scope embedding permission',
                'ordering': ['application_scope__name', 'provider__name'],
            },
        ),
        migrations.AddField(
            model_name='applicationscope',
            name='allow_external_embedding_corpus_egress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationscope',
            name='allow_external_embedding_query_egress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgecollection',
            name='external_embedding_egress_policy',
            field=models.CharField(choices=[('inherit', 'Inherit the application scope decision'), ('deny', 'Deny external embedding egress for this collection')], default='inherit', max_length=20),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='declared_locality',
            field=models.CharField(choices=[('unknown', 'Unknown (not classified - embeddings denied)'), ('local', 'Local (inside the declared trust boundary)'), ('external', 'External (crosses the trust boundary)')], default='unknown', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='applicationscope',
            constraint=models.CheckConstraint(condition=models.Q(('allow_external_embedding_query_egress', False), ('allow_external_embedding_corpus_egress', True), _connector='OR'), name='ai_hub_query_egress_subset_of_corpus'),
        ),
        migrations.AddField(
            model_name='providergrant',
            name='application_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_grants', to='ai_hub.applicationscope'),
        ),
        migrations.AddField(
            model_name='providergrant',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_grants', to='ai_hub.providerconfig'),
        ),
        migrations.AddConstraint(
            model_name='providergrant',
            constraint=models.UniqueConstraint(fields=('application_scope', 'provider'), name='ai_hub_unique_scope_provider_grant'),
        ),
    ]
