# Generated by Django 6.1 on 2026-08-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0026_embedding_egress_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('model_name', models.CharField(max_length=140)),
                ('model_revision', models.CharField(max_length=140)),
                ('vector_dimension', models.PositiveIntegerField()),
                ('distance_metric', models.CharField(choices=[('cosine', 'Cosine'), ('dot_product', 'Dot product'), ('euclidean', 'Euclidean')], max_length=20)),
                ('normalization', models.CharField(choices=[('none', 'None (no additional transform)'), ('l2', 'L2 normalize')], max_length=20)),
                ('max_input_chars', models.PositiveIntegerField(default=8000)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embedding_models', to='ai_hub.providerconfig')),
            ],
            options={
                'verbose_name': '1.2c Embedding model config',
                'verbose_name_plural': '1.2c Embedding model configs - vector-space contracts',
                'ordering': ['name'],
            },
        ),
    ]
