# Generated by Django 6.1 on 2026-08-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0027_embedding_model_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k1', models.CharField(max_length=80)),
                ('e1', models.CharField(max_length=80)),
                ('vector_dimension', models.PositiveIntegerField()),
                ('vector_format', models.CharField(choices=[('f32le1', 'IEEE-754 float32, little endian, v1')], default='f32le1', max_length=20)),
                ('vector_bytes', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='ai_hub.applicationscope')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ai_hub.knowledgedocumentchunk')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='ai_hub.knowledgecollection')),
                ('embedding_model_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunk_embeddings', to='ai_hub.embeddingmodelconfig')),
            ],
            options={
                'verbose_name': '1.5b Knowledge chunk embedding',
                'verbose_name_plural': '1.5b Knowledge chunk embeddings - derived index state',
                'ordering': ['application_scope__name', 'collection__name', 'chunk_id'],
                'indexes': [models.Index(fields=['application_scope', 'e1'], name='aihub_cemb_scope_e1_idx'), models.Index(fields=['application_scope', 'collection', 'e1'], name='aihub_cemb_scope_coll_e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('chunk', 'e1'), name='ai_hub_unique_chunk_e1_vector'), models.CheckConstraint(condition=models.Q(('vector_dimension__gte', 1)), name='ai_hub_chunk_embedding_dimension_positive')],
            },
        ),
    ]
