# Generated by Django 6.1 on 2026-08-30 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0028_knowledge_chunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id_snapshot', models.PositiveBigIntegerField()),
                ('workspace_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('embedding_model_config_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('requested_limit', models.PositiveSmallIntegerField()),
                ('evidence_version', models.CharField(max_length=32)),
                ('fusion_version', models.CharField(max_length=32)),
                ('rrf_k', models.PositiveIntegerField()),
                ('branch_depth', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('application_scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_runs', to='ai_hub.applicationscope')),
            ],
            options={
                'verbose_name': '5.1 Retrieval run',
                'verbose_name_plural': '5.1 Retrieval runs',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('completed', 'Completed'), ('refused', 'Refused')], max_length=20)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('degraded', models.BooleanField(default=False)),
                ('lexical_status', models.CharField(blank=True, max_length=32)),
                ('semantic_status', models.CharField(blank=True, max_length=32)),
                ('semantic_failure_kind', models.CharField(blank=True, max_length=32)),
                ('failure_category', models.CharField(blank=True, max_length=64)),
                ('e1', models.CharField(blank=True, max_length=80)),
                ('semantic_metric', models.CharField(blank=True, max_length=20)),
                ('lexical_candidates_scanned', models.PositiveIntegerField(default=0)),
                ('lexical_candidates_truncated', models.BooleanField(default=False)),
                ('semantic_candidate_count', models.PositiveIntegerField(default=0)),
                ('semantic_scored_count', models.PositiveIntegerField(default=0)),
                ('returned_count', models.PositiveSmallIntegerField(default=0)),
                ('retrieval_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='ai_hub.retrievalrun')),
            ],
            options={
                'verbose_name': '5.3 Retrieval outcome',
                'verbose_name_plural': '5.3 Retrieval outcomes',
                'ordering': ['-finished_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id_snapshot', models.PositiveBigIntegerField()),
                ('document_id_snapshot', models.PositiveBigIntegerField()),
                ('collection_id_snapshot', models.PositiveBigIntegerField()),
                ('k1', models.CharField(max_length=80)),
                ('final_rank', models.PositiveSmallIntegerField()),
                ('lexical_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semantic_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('retrieval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='ai_hub.retrievalrun')),
            ],
            options={
                'verbose_name': '5.4 Retrieval hit',
                'verbose_name_plural': '5.4 Retrieval hits',
                'ordering': ['retrieval_run_id', 'final_rank'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalRunCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id_snapshot', models.PositiveBigIntegerField()),
                ('retrieval_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_collections', to='ai_hub.retrievalrun')),
            ],
            options={
                'verbose_name': '5.2 Retrieval run collection',
                'verbose_name_plural': '5.2 Retrieval run collections',
                'ordering': ['collection_id_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='retrievalrun',
            index=models.Index(fields=['application_scope', 'started_at'], name='aihub_retrun_scope_time_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalhit',
            index=models.Index(fields=['chunk_id_snapshot'], name='aihub_rethit_chunk_idx'),
        ),
        migrations.AddConstraint(
            model_name='retrievalhit',
            constraint=models.UniqueConstraint(fields=('retrieval_run', 'final_rank'), name='ai_hub_unique_retrieval_hit_rank'),
        ),
        migrations.AddConstraint(
            model_name='retrievalhit',
            constraint=models.UniqueConstraint(fields=('retrieval_run', 'chunk_id_snapshot'), name='ai_hub_unique_retrieval_hit_chunk'),
        ),
        migrations.AddConstraint(
            model_name='retrievalhit',
            constraint=models.CheckConstraint(condition=models.Q(('final_rank__gte', 1)), name='ai_hub_retrieval_hit_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='retrievalhit',
            constraint=models.CheckConstraint(condition=models.Q(('lexical_rank__isnull', True), ('lexical_rank__gte', 1), _connector='OR'), name='ai_hub_retrieval_hit_lexical_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='retrievalhit',
            constraint=models.CheckConstraint(condition=models.Q(('semantic_rank__isnull', True), ('semantic_rank__gte', 1), _connector='OR'), name='ai_hub_retrieval_hit_semantic_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='retrievalhit',
            constraint=models.CheckConstraint(condition=models.Q(('lexical_rank__isnull', False), ('semantic_rank__isnull', False), _connector='OR'), name='ai_hub_retrieval_hit_has_a_branch'),
        ),
        migrations.AddConstraint(
            model_name='retrievalruncollection',
            constraint=models.UniqueConstraint(fields=('retrieval_run', 'collection_id_snapshot'), name='ai_hub_unique_retrieval_run_collection'),
        ),
    ]
