# Generated by Django 6.1 on 2026-10-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0030_pgvector_ann_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationscope',
            name='retrieval_embedding_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retrieval_scopes', to='ai_hub.embeddingmodelconfig'),
        ),
    ]
