# Generated by Django 6.0.6 on 2026-06-17 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_hub', '0002_alter_providerconfig_provider_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('anchor', models.SlugField(max_length=300)),
                ('body_markdown', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('search_text', models.TextField(blank=True)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documentation chunk',
                'verbose_name_plural': 'Documentation chunks',
                'ordering': ['page__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('source_path', models.CharField(max_length=500)),
                ('body_markdown', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documentation page',
                'verbose_name_plural': 'Documentation pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documentation source',
                'verbose_name_plural': 'Documentation sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TutorialModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tutorial module',
                'verbose_name_plural': 'Tutorial modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat session',
                'verbose_name_plural': 'Chat sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_execution_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_chat_messages', to='ai_hub.executionsession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='academy.documentationchatsession')),
                ('retrieved_chunks', models.ManyToManyField(blank=True, related_name='chat_messages', to='academy.documentationchunk')),
            ],
            options={
                'verbose_name': 'Chat message',
                'verbose_name_plural': 'Chat messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentationchunk',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='academy.documentationpage'),
        ),
        migrations.AddField(
            model_name='documentationpage',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='academy.documentationsource'),
        ),
        migrations.CreateModel(
            name='TutorialMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('goal', models.TextField()),
                ('instructions_markdown', models.TextField()),
                ('validation_key', models.CharField(max_length=100)),
                ('starter_data_key', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('related_docs', models.ManyToManyField(blank=True, related_name='missions', to='academy.documentationpage')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='academy.tutorialmodule')),
            ],
            options={
                'verbose_name': 'Tutorial mission',
                'verbose_name_plural': 'Tutorial missions',
                'ordering': ['module__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_feedback', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='academy.tutorialmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission progress',
                'verbose_name_plural': 'Mission progress records',
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
