# Generated by Django 6.0.6 on 2026-06-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('ai_hub', '0002_alter_providerconfig_provider_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('prompt', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('evaluation_rubric', models.TextField(help_text="Instructions the AI evaluator uses to score and comment on the user's answer.")),
                ('hint', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('requires_api', models.BooleanField(default=True, help_text='Uncheck if this exercise works with the Training provider (no real API key needed).')),
                ('is_active', models.BooleanField(default=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_exercises', to='academy.tutorialmission')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_exercises', to='academy.tutorialmodule')),
            ],
            options={
                'verbose_name': 'Lab exercise',
                'verbose_name_plural': 'Lab exercises',
                'ordering': ['module__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LabAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('user_input', models.TextField()),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_score', models.CharField(choices=[('pass', 'Pass'), ('partial', 'Partial'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('follow_up_question', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_attempts', to='ai_hub.executionsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_attempts', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academy.labexercise')),
            ],
            options={
                'verbose_name': 'Lab attempt',
                'verbose_name_plural': 'Lab attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
