# Generated by Django 6.0.6 on 2026-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_labexercise_labattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
