# Generated by Django 6.0.6 on 2026-06-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_hub', '0002_alter_providerconfig_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('analysing', 'Analysing'), ('triaged', 'Triaged'), ('closed', 'Closed')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket', to='ai_hub.executionsession')),
            ],
            options={
                'verbose_name': 'Support ticket',
                'verbose_name_plural': 'Support tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='support_demo.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket analysis',
                'verbose_name_plural': 'Ticket analyses',
            },
        ),
    ]
